apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-iot-db
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: overlays/iot
    repoURL: https://github.com/wep4you/prometheus-kustomize.git
    targetRevision: main
  destination:
    namespace: iot-prometheus
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
