apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wep4you-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: local
    repoURL: https://github.com/wep4you/k8s-apps.git
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
